import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/provider";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <nav className="bg-gray-800 p-4">
            <div className="container mx-auto flex items-center justify-between">
              <div className="text-white font-semibold text-lg">My App</div>
              <div className="flex">
                <Link href="/users" className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Users</Link>
                <Link href="/todo" className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Todo</Link>
              </div>
            </div>
          </nav>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </div>

      </body>
    </html>
  );
}
